### ISSUE TITLE
Error: sass: not found

### ISSUE THREAD

**Issue by E2design** [Dolphiq/craft3-iconpicker#4]
Getting this error while trying to use the field form within an entry.

Apparently icon picker adds a fonts.scss file to the ../resources-shared/css folder while it's looking for a fonts.css file. Renaming the fonts.scss into fonts.css solved the issue for now.

`yii\base\Exception: AssetConverter command 'sass '/storage/av04180/www/thetag_html/public/cpresources/dcdddca4/9b8c8840/css/fonts.scss' '/storage/av04180/www/thetag_html/public/cpresources/dcdddca4/9b8c8840/css/fonts.css' --sourcemap' failed with exit code 127:
STDOUT:

STDERR:
sh: 1: sass: not found
 in /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/web/AssetConverter.php:113
Stack trace:
#0 /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/web/AssetConverter.php(69): yii\web\AssetConverter->runCommand('sass '/storage/...', '/storage/av0418...', 'css/fonts.scss', 'css/fonts.css')
#1 /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/web/AssetBundle.php(210): yii\web\AssetConverter->convert('css/fonts.scss', '/storage/av0418...')
#2 /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/web/AssetManager.php(268): yii\web\AssetBundle->publish(Object(craft\web\AssetManager))
#3 /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/web/AssetManager.php(239): yii\web\AssetManager->loadBundle('plugins\\dolphiq...', Array, true)
#4 /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/web/View.php(286): yii\web\AssetManager->getBundle('plugins\\dolphiq...')
#5 /storage/av04180/www/thetag_html/vendor/dolphiq/iconpicker/src/fields/Iconpicker.php(299): yii\web\View->registerAssetBundle('plugins\\dolphiq...')
#6 /storage/av04180/www/thetag_html/vendor/dolphiq/iconpicker/src/views/main/_field.php(14): plugins\dolphiq\iconpicker\fields\Iconpicker->getFontCss()
#7 /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/base/View.php(332): require('/storage/av0418...')
#8 /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/storage/av0418...', Array)
#9 /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/storage/av0418...', Array, NULL)
#10 /storage/av04180/www/thetag_html/vendor/dolphiq/iconpicker/src/fields/Iconpicker.php(133): yii\base\View->render('@vendor/dolphiq...', Array)
#11 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Extension/Core.php(1595): plugins\dolphiq\iconpicker\fields\Iconpicker->getInputHtml(Object(plugins\dolphiq\iconpicker\models\IconpickerModel), Object(craft\elements\Entry))
#12 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/helpers/Template.php(76): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(plugins\dolphiq\iconpicker\fields\Iconpicker), 'getInputHtml', Array, 'method', false, false)
#13 /storage/av04180/www/thetag_html/storage/runtime/compiled_templates/f4/f40bf7aa3da8ba1d0d5709a7d6b6ba11c14088c2790930631112b0bd2fcf74d6.php(42): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(plugins\dolphiq\iconpicker\fields\Iconpicker), 'getInputHtml', Array, 'method')
#14 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_11ac9df8ba56b3c88fa8de2d8a8742b0105ed5ae6c2863c14b1e0152fae8eaf7->doDisplay(Array, Array)
#15 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#16 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#17 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#18 /storage/av04180/www/thetag_html/storage/runtime/compiled_templates/e8/e83ebc22efbaff06b9e9dcd9d07d32627743bafac81e481ec71f4a5e2a819a1c.php(43): craft\web\twig\Template->display(Array)
#19 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_28f8512f5e6ec06dd86bb2f0e3bad54b8e572236e03be5a9d8bf21702e84a7ea->doDisplay(Array, Array)
#20 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#21 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#22 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#23 /storage/av04180/www/thetag_html/storage/runtime/compiled_templates/34/34e9036e01bcabc01f3a0966523ae8b02573f6e92993d0dff823c13bf3b13684.php(55): craft\web\twig\Template->display(Array)
#24 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_84676e348a55b35df902cfda578b7f49eefc0a4bf224d240cc7680188607dcdc->doDisplay(Array, Array)
#25 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#26 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#27 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#28 /storage/av04180/www/thetag_html/storage/runtime/compiled_templates/69/6905d742f01d31749b07a16e9a64609a83ec0839bbb85201fb60654dbf3ddc29.php(430): craft\web\twig\Template->display(Array)
#29 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(188): __TwigTemplate_9a711c33af4b47997f533a8573011726832ce5db1d42f8f48a67411222cc7763->block_content(Array, Array)
#30 /storage/av04180/www/thetag_html/storage/runtime/compiled_templates/73/73134d11f67e8d0d2da083a34c92e74d889d8aa3f61a0360aedb91663b0a9b07.php(746): Twig_Template->displayBlock('content', Array, Array)
#31 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(188): __TwigTemplate_e954359236908fb2903049e0b3af3285d602715fce630d36c590f0f09530adec->block_main(Array, Array)
#32 /storage/av04180/www/thetag_html/storage/runtime/compiled_templates/73/73134d11f67e8d0d2da083a34c92e74d889d8aa3f61a0360aedb91663b0a9b07.php(643): Twig_Template->displayBlock('main', Array, Array)
#33 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(188): __TwigTemplate_e954359236908fb2903049e0b3af3285d602715fce630d36c590f0f09530adec->block_body(Array, Array)
#34 /storage/av04180/www/thetag_html/storage/runtime/compiled_templates/33/335a8d54e1de8b8a851f17eb891280c15e6a72398d84be47a892890baf8aa839.php(53): Twig_Template->displayBlock('body', Array, Array)
#35 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_9e386509e6eb59386b8b18514a45d0df7089cf0fa9fd3769729ffd0cde937301->doDisplay(Array, Array)
#36 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#37 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#38 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#39 /storage/av04180/www/thetag_html/storage/runtime/compiled_templates/fe/feb527bbe5b4bbd28c789276110e15560c22b7cb1c07ac2db0fc61613c047e12.php(36): craft\web\twig\Template->display(Array, Array)
#40 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_b808e2aeeb3c362d5a10098da526ec0fd942cb21efa244973005266840e46510->doDisplay(Array, Array)
#41 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#42 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#43 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#44 /storage/av04180/www/thetag_html/storage/runtime/compiled_templates/73/73134d11f67e8d0d2da083a34c92e74d889d8aa3f61a0360aedb91663b0a9b07.php(88): craft\web\twig\Template->display(Array, Array)
#45 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_e954359236908fb2903049e0b3af3285d602715fce630d36c590f0f09530adec->doDisplay(Array, Array)
#46 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#47 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#48 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#49 /storage/av04180/www/thetag_html/storage/runtime/compiled_templates/69/6905d742f01d31749b07a16e9a64609a83ec0839bbb85201fb60654dbf3ddc29.php(58): craft\web\twig\Template->display(Array, Array)
#50 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_9a711c33af4b47997f533a8573011726832ce5db1d42f8f48a67411222cc7763->doDisplay(Array, Array)
#51 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#52 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#53 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#54 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
#55 /storage/av04180/www/thetag_html/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#56 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/View.php(292): Twig_Environment->render('entries/_edit', Array)
#57 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/View.php(340): craft\web\View->renderTemplate('entries/_edit', Array)
#58 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/Controller.php(121): craft\web\View->renderPageTemplate('entries/_edit', Array)
#59 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/controllers/EntriesController.php(358): craft\web\Controller->renderTemplate('entries/_edit', Array)
#60 [internal function]: craft\controllers\EntriesController->actionEditEntry('tag_team', 11, NULL, NULL, NULL, Object(craft\elements\Entry))
#61 /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#62 /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#63 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('edit-entry', Array)
#64 /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#65 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/Application.php(242): yii\base\Module->runAction('entries/edit-en...', Array)
#66 /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#67 /storage/av04180/www/thetag_html/vendor/craftcms/cms/src/web/Application.php(207): yii\web\Application->handleRequest(Object(craft\web\Request))
#68 /storage/av04180/www/thetag_html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#69 /storage/av04180/www/thetag_html/public/index.php(23): yii\base\Application->run()
#70 {main}`

**Comment by johanzandstra** [comment]
@E2design I can not reproduce the error. 
can you please give me more information about:
- The Craft version you are using (Craft 3 RC2?)
- The location of the font
- The exception is when editing an item where the Field type is adjusted  the Control Panel right? 
- What about the use of the extension in twig template is that working alright?
sample template:
`{% do view.registerAssetBundle("plugins\\dolphiq\\iconpicker\\assets\\sharedAsset") %}
<html style="padding: 0; margin: 0;">
<head>
    <title></title>

    {{ head() }}

</head>

<body>

{{ beginBody() }}

{% if entry.iconPickerField.icon %}
    Hex: {{ entry.iconPickerField.icon }}<br>
    {{ entry.iconPickerField.iconSpan|raw }}
{% endif %}

{{ endBody() }}

</body>
</html>`

**Comment by E2design** [comment]
- Craft 3 RC2
- Exception occurs while opening an entry where the icon field is attached to
- Not using the front-end (templates) yet
- Location of the fonts:

![schermafdruk 2017-12-14 16 43 10](https://user-images.githubusercontent.com/5907530/34000568-f28c2ec2-e0ed-11e7-9e35-13c782e1f7e9.png)

**Comment by johanzandstra** [comment]
looks correct to me, can you please update the plugin (just released an update this can fix the problem

**Comment by E2design** [comment]
Done
