### ISSUE TITLE
Font Awesome 4/5

### ISSUE THREAD

**Issue by GuidoNeele** [Dolphiq/craft3-iconpicker#6]
Do you have an example of how to use this plugin to show font awesome icons on a website? The iconClass is not returning the class names that are needed when using the <i> tags.

Thanks

**Comment by dolphiq-allard** [comment]
Hi Guido,

Thanks for your reply. We'll look into this one and keep you posted!

Cheers

**Comment by GuidoNeele** [comment]
Figured out what I did wrong. Forgot to add `{% do view.registerAssetBundle("plugins\\dolphiq\\iconpicker\\assets\\sharedAsset") %}`
Thought `iconClass` would return fa-users, guess I should've RTFM :-)

**Comment by dolphiq-allard** [comment]
No worries ;-)

Happens to all of us... Happy to see the plugin is working as intended. Thanks again.

Cheers
