### ISSUE TITLE
Does not display selection modal when marked as "required"

### ISSUE THREAD

**Issue by Pilipo** [Dolphiq/craft3-iconpicker#7]
I have built a simple matrix field type that contain two "plain text" fields and a single iconpicker. When I save everything and try to add the icon on the entry, the "pick an icon" button is unresponsive. 

I tested this as an independent field (outside of a matrix) and everything worked as expected. 

Any thoughts?

**Comment by Pilipo** [comment]
I juts realized that the issue is not the Matrix type. The actual issue is marking this iconpicker as required. When marked as required, the selection popup never triggers. I'm updating the issue title now to reflect this.

**Comment by jeffaglenn** [comment]
I'm getting what you had originally. Marking it required or not does not affect picking an icon. However if the field is within a Matrix the button is unresponsive. I don't seem to be getting any console errors either.

**Comment by E2design** [comment]
Same issue here. The button is visible but not responsive if placed within a matrix.

IconPicker 1.0.4
Craft Pro 3.0.11
PHP 7.1.12

**Comment by ewhicher** [comment]
Having a similar issue here, when the icon picker is within a matrix field it is not clickable until the page has been saved (or a save attempt has been triggered and the page is reloaded).

Any thoughts?

cms: v 3.0.13.1
iconpicker: v 1.0.4
php: v 7.1.12

**Comment by jeffaglenn** [comment]
Still haven't found a way around this. I'm thinking it may have something to do with the wrapping divs and when it's in the matrix field it doesn't have those divs/classes to look for. Just a guess?

**Comment by Luuc15** [comment]
Has been fixed with latest release
